using System;

namespace Server.Contracts
{
    /// <summary>
    /// Contains the details of PhotoEntry
    /// </summary>
    public class PhotoEntry
    {
        /// <summary>
        /// Reference Id of a single entry. This must be unique. Will be autogenerated if left empty
        /// </summary>
        public string ReferenceId { get; set; }

        /// <summary>
        /// Theme of the photo. This must correspond to <see cref="PhotoTheme"/>
        /// </summary>
        public string Theme { get; set; }

        /// <summary>
        /// Details of the photographer who uploaded the photo
        /// </summary>
        public Photographer Photographer { get; set; }

        /// <summary>
        /// Reference Id of the associated photo. This should always be valid.
        /// </summary>
        public string FileId { get; set; }

        /// <summary>
        /// A creative caption to go in with your photo
        /// </summary>
        public string Caption { get; set; }

        /// <summary>
        /// Date and time of the upload
        /// </summary>
        public DateTime UploadedOn { get; set; }
    }
}
