#region

using System;
using System.ComponentModel.DataAnnotations;

#endregion

namespace PhotoContest.Web.Contracts;

/// <summary>
///     Contains the details of Submission
/// </summary>
public class Submission
{
    /// <summary>
    ///     Contest of the photo. This must correspond to <see cref="Contracts.Contest" />
    /// </summary>
    [Required]
    public Contest Contest { get; set; }

    /// <summary>
    ///     Reference Id of the associated photo. This should always be valid.
    /// </summary>
    [Required]
    public string FileId { get; set; }

    /// <summary>
    ///     A creative caption to go in with your photo
    /// </summary>
    [Required]
    public string Caption { get; set; }

    /// <summary>
    ///     Date and time of the upload
    /// </summary>
    public DateTime? UploadedOn { get; set; }
    
#nullable enable
    /// <summary>
    ///     Reference Id of a single entry. This must be unique. Will be autogenerated if left empty
    /// </summary>
    public string? ReferenceId { get; set; }

    /// <summary>
    ///     Details of the photographer who uploaded the photo
    /// </summary>
    public Photographer? Photographer { get; set; }
#nullable disable
}